#-----------------------------------------------------------------------------
# MARKOV MAKEFILES
#----------------------------------------------------------------------------

all:
	
	make -C markov_cpp 
	make -C markov_py

clean:
	
	make -C markov_cpp clean
	make -C markov_java clean
run:

	make -C markov_cpp run
	make -C markov_py run
